properties:
  !key:by-name Maven Info Plugin Configuration:
    assignName: false
    assignDescription: false
  jenkins-model-BuildDiscarderProperty:
    specified: false
    strategy:
      $class: !by-name Log Rotation
  !key:by-name Rebuild Settings:
    autoRebuild: false
    rebuildDisabled: false
  !key:by-name This project is parameterized:
    specified: false
disable: false
concurrentBuild: false
jdk: (System)
hasCustomQuietPeriod: false
quiet_period: 5
hasCustomScmCheckoutRetryCount: false
scmCheckoutRetryCount: 0
blockBuildWhenUpstreamBuilding: false
blockBuildWhenDownstreamBuilding: false
!key:by-name Maven release build:
  releaseGoals: -Dresume=false release:prepare release:perform
  dryRunGoals: -Dresume=false -DdryRun=true release:prepare
  numberOfReleaseBuildsToKeep: 1
  defaultVersioningMode: None
  selectCustomScmCommentPrefix: false
  selectAppendHudsonUsername: false
  selectScmCredentials: false
  releaseEnvVar: IS_M2RELEASEBUILD
!key:by-name Unleash:
  goals: unleash:perform
  useLogTimestamps: true
  preselectUseGlobalVersion: false
  preselectUseCustomScmCredentials: false
  preselectAllowLocalReleaseArtifacts: true
  preselectCommitBeforeTagging: false
  tagNamePattern: @{project.version}
  scmMessagePrefix: [unleash-maven-plugin]
rootPOM: pom.xml
mavenOpts: -Xmx3072m -Xms1024m -XX:+TieredCompilation -XX:TieredStopAtLevel=1
usePrivateRepository: false
explicitLocalRepository:
  $class: !by-name Default (~/.m2/repository)
hasCustomWorkspace: false
validationLevel: -1
settings:
  $class: !by-name Use default maven settings
globalSettings:
  $class: !by-name Use default maven global settings
runIfResult: failure
$class: !by-name Maven project
